### ISSUE TITLE
Dockerize a running instance of statusd

### ISSUE THREAD

**Issue by adriacidre** [status-im/status-go-sdk#1]
SDK it's accessing status node through IPC calls, in order to make it easy to develop on top of it we need a docker image with a running node exposing private rpc methods.

**Comment by gravityblast** [comment]
do we need a `statusd` node, or can we have a standard `geth` node running whisper V6?
So that we don't need to change `status-go`, and we don't need to expose other RPC methods.

**Comment by adriacidre** [comment]
We need, at least, access to RPC [status_login](https://github.com/status-im/status-go/pull/877/files#diff-cba9feba52670bdc6d5240d5aec0641cR55) and [status_signup](https://github.com/status-im/status-go/pull/877/files#diff-cba9feba52670bdc6d5240d5aec0641cR86)

**Comment by gravityblast** [comment]
I'm not sure we need to implement login and signup in status.
To interact with whisper a bot only needs a key pair to be able to sign messages and receive contact requests, so a bot can already have a key pair or can call `shh_new_key_pair`.

If we avoid implementing the login/signup, a bot can manage its identity the way it wants, and we don't need to add this logic to `statusd` / `status-go`.

If we really want the `sdk` to be opinionated on the identities management, we can have this logic in the sdk but still not in the status node.
