### ISSUE TITLE
Normalize RPCClient Call method

### ISSUE THREAD

**Issue by adriacidre** [status-im/status-go-sdk#10]
# Problem

Right now if you want to use a `"github.com/ethereum/go-ethereum/rpc"` as RPCClient to be injected to the SDK its a bit difficult as its call is something like:

```
c.rpc.Call(&response, request.Method, request.Args...)
```

and as our current implementation receives:

```
Call(request interface{}) (response interface{}, err error)
```
is not easy to get the data on request to call geth rpc

# Implementation

So, as all calls to this method happen now from [dictionary.go](https://github.com/status-im/status-go-sdk/blob/master/dictionary.go#L71) they're centralized and isolated. 

All of them are using a `shhRequest` struct to compose messages then they marshal it, and the result is sent to this call method.

We should change the call method to accept `sshRequest` (Rename it to `Request`) instead of an interface (string), this will allow us to remove all `json.Marshal` on each dictionary method. Additionally making shhRequest public, so, this method will look something like:

```go
Call(request Request) (response interface{}, err error)
```

**Comment by pilu** [comment]
>Right now if you want to use a "github.com/ethereum/go-ethereum/rpc" as RPCClient to be injected to the SDK its a bit difficult as its call is something like:
> `c.rpc.Call(&response, request.Method, request.Args...)`

So is it ok to use this signature for the interface?

**Comment by gravityblast** [comment]
@adriacidre don't we need it anymore?
