### ISSUE TITLE
pinger ponger recovery

### ISSUE THREAD

**Issue by adriacidre** [status-im/status-go-sdk#11]
# Problem

`pinger/main.go and `ponger/main.go` are deprecated now, once we have https://github.com/status-im/status-go-sdk/issues/10 fixed they should be adapted to use geth rpc client.

# Implementation

We should be able to use something like 
```
type RemoteClient struct {
    rpcClient rpcClient
}

func newRemoteClient(rawurl string) (*RemoteClient, error) {
    c, err := rpc.Dial(rawurl)
    if err != nil {
        return nil, err
    }

    return &RemoteClient{c}, nil
}

func (c *RemoteClient) Call(request *sdk.Request) (response interface{}, err error) {
    c.rpc.Call(&response, request.Method, request.Args...)
    return
}
```
so its injected to the sdk creation like:
```
sdk.New(newRemoteClient("localhost:999"))
```

# Acceptance Criteria

Pinger publishes messages on the desired channel.
Ponger responds pinger published messages on the same channel.

**Comment by gravityblast** [comment]
>```
>func (c *RemoteClient) Call(request *sdk.Request) (response interface{}, err error) {
>    c.rpc.Call(&response, request.Method, request.Args...)
>    return
>}

The problem with this is that the response types are defined in the sdk.
So the sdk would end up doing:

```
req := &Request{
	Method: "status_signup",
	Params: &statusSignupParam{Password: password},
}

resp, err := sdk.RPCClient.Call(req)
```

and here `resp` will be an interface, so the sdk will need a type assertion.

We can change it to be:

```
var resp signupResponse

req := &Request{
	Method: "status_signup",
	Params: &statusSignupParam{Password: password},
}

err := sdk.RPCClient.Call(req, &resp)
```

so that the sdk knows the type, and the `remoteClient` only need to decode the response without knowing the type.
