### ISSUE TITLE
Basic test suite

### ISSUE THREAD

**Issue by adriacidre** [status-im/status-go-sdk#18]
# Problem

Actually this is a really unstable package as we don't have a proper test suite.

# Implementation

Following Makefile policy on `status-go` we should be able to run tests with a make command like `make test`

# Notes

Add a note on testing to the readme

# Future Steps

Integrate CI for this tests

**Comment by pedropombeiro** [comment]
Will there be other PRs addressing this issue, or can it be closed?

**Comment by adriacidre** [comment]
nope, closed :)
