### ISSUE TITLE
Implement double ratchet as first step to Forward Secrecy

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-go-sdk#35]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to have encryption keys changed regularly so that if an eavesdropper records the encrypted envelopes and later gets my private key, he's still not able to decrypt the full conversation.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: PFS entails 3 phases:
- initial key exchange
- authentication
- double ratcheting

This GHI only takes care of the 3rd phase, as for the first two ones we'll need some form of storage (eventually Swarm or IPFS, but maybe a temporary compromise on some other provider).

See discussion in https://discuss.status.im/t/forward-secrecy/150.

#### Expected behavior
[comment]: # (Describe what you expected to happen.)

Each time a message is exchanged, new encryption keys are computed (session duration corresponds to one message). 

#### Actual behavior
[comment]: # (Describe what actually happened.)

The same encryption keys are used for the duration of the chat session (session is indefinite).

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*: 

We should investigate using the existing untested implementation in https://github.com/status-im/doubleratchet. This GHI is blocked by https://github.com/status-im/status-go-sdk/issues/34

**Comment by cammellos** [comment]
Closing this as implemented
