### ISSUE TITLE
Implement X3DH key exchange

### ISSUE THREAD

**Issue by pedropombeiro** [status-im/status-go-sdk#36]
# Problem

We need to implement the [X3DH](https://signal.org/docs/specifications/x3dh/) key agreement protocol in order to increase security.

# Implementation

Known steps towards feature implementation.
What needs further specifying and investigating.

# Acceptance Criteria

Rules for the future PR to be accepted.

# Notes

Random notes to keep in mind while implementing it. Mostly about related issues and future plans and thoughts.

# Future Steps

Steps which should be taken after this issue has been resolved.

**Comment by cammellos** [comment]
Closing this as implemented
